class Custom_error(Exception):
    pass